// components/AnalysisPDF.jsx — PDF document for credit analysis export
import { Document, Page, View, Text, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: 'Helvetica',
  },
  header: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  subheader: {
    fontSize: 11,
    color: '#6B7280',
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    marginTop: 16,
    marginBottom: 6,
    color: '#1D4ED8',
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    borderBottomStyle: 'solid',
    marginBottom: 12,
  },
  label: {
    fontWeight: 'bold',
    fontSize: 11,
  },
  value: {
    fontSize: 11,
    marginBottom: 6,
    lineHeight: 1.5,
  },
  bulletItem: {
    fontSize: 11,
    marginBottom: 4,
    paddingLeft: 12,
  },
  verdict: {
    fontSize: 13,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  footer: {
    fontSize: 9,
    color: '#9CA3AF',
    marginTop: 30,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    borderTopStyle: 'solid',
    paddingTop: 8,
  },
});

export function AnalysisPDF({ analysis, leadId }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* 1. Header */}
        <Text style={styles.header}>FUNDING SATHI</Text>
        <Text style={styles.subheader}>
          Credit Analysis Report  |  Lead ID: {leadId || 'N/A'}
        </Text>
        <View style={styles.divider} />

        {/* 2. Deal Viability */}
        <Text style={styles.sectionTitle}>DEAL VIABILITY</Text>
        <Text style={styles.verdict}>{analysis.dealViability.verdict}</Text>
        <Text style={styles.value}>{analysis.dealViability.rationale}</Text>

        {/* 3. Lender Recommendation */}
        <Text style={styles.sectionTitle}>LENDER RECOMMENDATION</Text>
        <Text style={styles.value}>
          <Text style={styles.label}>Primary: </Text>
          {analysis.lenderRecommendation.primary}
        </Text>
        {analysis.lenderRecommendation.secondary && (
          <Text style={styles.value}>
            <Text style={styles.label}>Secondary: </Text>
            {analysis.lenderRecommendation.secondary}
          </Text>
        )}
        <Text style={styles.value}>
          {analysis.lenderRecommendation.justification}
        </Text>

        {/* 4. Risk Flags */}
        <Text style={styles.sectionTitle}>RISK FLAGS</Text>
        {analysis.riskFlags.map((flag, i) => (
          <Text key={i} style={styles.bulletItem}>•  {flag}</Text>
        ))}

        {/* 5. Document Checklist */}
        <Text style={styles.sectionTitle}>DOCUMENT CHECKLIST</Text>
        {analysis.documentChecklist.map((doc, i) => (
          <Text key={i} style={styles.bulletItem}>•  {doc}</Text>
        ))}

        {/* 6. RM Next Action */}
        <Text style={styles.sectionTitle}>RM NEXT ACTION</Text>
        <Text style={styles.value}>{analysis.rmNextAction}</Text>

        {/* 7. Footer */}
        <Text style={styles.footer}>
          Generated by Funding Sathi  |  {new Date().toLocaleDateString('en-IN')}
        </Text>
      </Page>
    </Document>
  );
}
