// components/AnalysisPDF.jsx — PDF document for credit analysis export
import { Document, Page, View, Text, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: 'Helvetica',
  },
  header: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  subheader: {
    fontSize: 11,
    color: '#6B7280',
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    marginTop: 16,
    marginBottom: 6,
    color: '#1D4ED8',
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    borderBottomStyle: 'solid',
    marginBottom: 12,
  },
  label: {
    fontWeight: 'bold',
    fontSize: 11,
  },
  value: {
    fontSize: 11,
    marginBottom: 6,
    lineHeight: 1.5,
  },
  bulletItem: {
    fontSize: 11,
    marginBottom: 4,
    paddingLeft: 12,
  },
  verdict: {
    fontSize: 13,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  footer: {
    fontSize: 9,
    color: '#9CA3AF',
    marginTop: 30,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    borderTopStyle: 'solid',
    paddingTop: 8,
  },
});

export function AnalysisPDF({ analysis, leadId }) {
  if (!analysis) {
    return (
      <Document>
        <Page size="A4" style={styles.page}>
          <Text style={styles.header}>FUNDING SATHI</Text>
          <Text style={styles.subheader}>
            Credit Analysis Report  |  Lead ID: {leadId || 'N/A'}
          </Text>
          <View style={styles.divider} />
          <Text style={styles.value}>No analysis data available yet.</Text>
        </Page>
      </Document>
    );
  }

  const dealViability = analysis.dealViability || {};
  const lenderRecommendation = analysis.lenderRecommendation || {};
  const riskFlags = analysis.riskFlags || [];
  const documentChecklist = analysis.documentChecklist || [];
  const rmNextAction = analysis.rmNextAction || '';

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* 1. Header */}
        <Text style={styles.header}>FUNDING SATHI</Text>
        <Text style={styles.subheader}>
          Credit Analysis Report  |  Lead ID: {leadId || 'N/A'}
        </Text>
        <View style={styles.divider} />

        {/* 2. Deal Viability */}
        <Text style={styles.sectionTitle}>DEAL VIABILITY</Text>
        <Text style={styles.verdict}>{dealViability.verdict || 'N/A'}</Text>
        <Text style={styles.value}>{dealViability.rationale || 'N/A'}</Text>

        {/* 3. Lender Recommendation */}
        <Text style={styles.sectionTitle}>LENDER RECOMMENDATION</Text>
        <Text style={styles.value}>
          <Text style={styles.label}>Primary: </Text>
          {lenderRecommendation.primary || 'N/A'}
        </Text>
        {lenderRecommendation.secondary && (
          <Text style={styles.value}>
            <Text style={styles.label}>Secondary: </Text>
            {lenderRecommendation.secondary}
          </Text>
        )}
        <Text style={styles.value}>
          {lenderRecommendation.justification || 'N/A'}
        </Text>

        {/* 4. Risk Flags */}
        <Text style={styles.sectionTitle}>RISK FLAGS</Text>
        {riskFlags.length > 0 ? (
          riskFlags.map((flag, i) => (
            <Text key={i} style={styles.bulletItem}>•  {flag}</Text>
          ))
        ) : (
          <Text style={styles.value}>No risk flags reported.</Text>
        )}

        {/* 5. Document Checklist */}
        <Text style={styles.sectionTitle}>DOCUMENT CHECKLIST</Text>
        {documentChecklist.length > 0 ? (
          documentChecklist.map((doc, i) => (
            <Text key={i} style={styles.bulletItem}>•  {doc}</Text>
          ))
        ) : (
          <Text style={styles.value}>No documents requested.</Text>
        )}

        {/* 6. RM Next Action */}
        <Text style={styles.sectionTitle}>RM NEXT ACTION</Text>
        <Text style={styles.value}>{rmNextAction || 'N/A'}</Text>

        {/* 7. Footer */}
        <Text style={styles.footer}>
          Generated by Funding Sathi  |  {new Date().toLocaleDateString('en-IN')}
        </Text>
      </Page>
    </Document>
  );
}
