// utils/formatAnalysisForClipboard.js — Formats analysis output as plain text for clipboard

/**
 * Formats a parsed credit analysis object into a human-readable
 * plain-text string suitable for pasting into emails, Slack, etc.
 *
 * @param {object} analysis — The parsed analysis object (from parseAnalysis).
 * @param {string} leadId   — The generated lead identifier.
 * @returns {string} A formatted multi-line string ready for the clipboard.
 */
export function formatAnalysisForClipboard(analysis, leadId) {
  if (!analysis) {
    return `FUNDING SATHI — CREDIT ANALYSIS\nLead ID: ${leadId || 'N/A'}\n─────────────────────────────────────────\nNo analysis data available.`;
  }

  const dealViability = analysis.dealViability || {};
  const lenderRecommendation = analysis.lenderRecommendation || {};
  const riskFlags = analysis.riskFlags || [];
  const documentChecklist = analysis.documentChecklist || [];
  const rmNextAction = analysis.rmNextAction || '';

  const lines = [
    `FUNDING SATHI — CREDIT ANALYSIS`,
    `Lead ID: ${leadId || 'N/A'}`,
    `─────────────────────────────────────────`,
    ``,
    `DEAL VIABILITY: ${dealViability.verdict || 'N/A'}`,
    dealViability.rationale || 'N/A',
    ``,
    `LENDER RECOMMENDATION`,
    `Primary: ${lenderRecommendation.primary || 'N/A'}`,
  ];

  if (lenderRecommendation.secondary) {
    lines.push(`Secondary: ${lenderRecommendation.secondary}`);
  }

  lines.push(
    `Justification: ${lenderRecommendation.justification || 'N/A'}`,
    ``,
    `RISK FLAGS`,
    ...(riskFlags.length > 0 ? riskFlags.map(flag => `• ${flag}`) : [`No risk flags reported.`]),
    ``,
    `DOCUMENT CHECKLIST`,
    ...(documentChecklist.length > 0 ? documentChecklist.map(doc => `• ${doc}`) : [`No documents requested.`]),
    ``,
    `RM NEXT ACTION`,
    rmNextAction || 'N/A',
    ``,
    `─────────────────────────────────────────`,
    `Generated by Funding Sathi`,
  );

  return lines.join('\n');
}
