// utils/formatAnalysisForClipboard.js — Formats analysis output as plain text for clipboard

/**
 * Formats a parsed credit analysis object into a human-readable
 * plain-text string suitable for pasting into emails, Slack, etc.
 *
 * @param {object} analysis — The parsed analysis object (from parseAnalysis).
 * @param {string} leadId   — The generated lead identifier.
 * @returns {string} A formatted multi-line string ready for the clipboard.
 */
export function formatAnalysisForClipboard(analysis, leadId) {
  const lines = [
    `FUNDING SATHI — CREDIT ANALYSIS`,
    `Lead ID: ${leadId || 'N/A'}`,
    `─────────────────────────────────────────`,
    ``,
    `DEAL VIABILITY: ${analysis.dealViability.verdict}`,
    analysis.dealViability.rationale,
    ``,
    `LENDER RECOMMENDATION`,
    `Primary: ${analysis.lenderRecommendation.primary}`,
  ];

  if (analysis.lenderRecommendation.secondary) {
    lines.push(`Secondary: ${analysis.lenderRecommendation.secondary}`);
  }

  lines.push(
    `Justification: ${analysis.lenderRecommendation.justification}`,
    ``,
    `RISK FLAGS`,
    ...analysis.riskFlags.map(flag => `• ${flag}`),
    ``,
    `DOCUMENT CHECKLIST`,
    ...analysis.documentChecklist.map(doc => `• ${doc}`),
    ``,
    `RM NEXT ACTION`,
    analysis.rmNextAction,
    ``,
    `─────────────────────────────────────────`,
    `Generated by Funding Sathi`,
  );

  return lines.join('\n');
}
